name: ci-deployment
on:
  pull_request:
    branches:
        - '*'
  push:
      branches:
        - master
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run npm install
        run: npm i
      - name: Run Angular test
        run: npm run test:ci
      - name: Run Build
        run: npm run build:ci
  deployment:
    runs-on: ubuntu-22.04
    if: github.ref == refs/heads/main' && github.event_name == 'push' && needs.ci.result == 'success'
    needs: [ci]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fake-angular-app:latest
